VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "Margin"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'--------------------------------------------------------------------------------
'    Component  : Margin
'    Project    : ViDock
'
'    Description: Describes a margin
'
'--------------------------------------------------------------------------------
Option Explicit

Public X_Overflow As Long

Public Y_Overflow As Long

Public Width      As Long

Public Height     As Long

Public X          As Long

Public Y          As Long

